version: '3.9'
services:
  api:
    image: openjdk:17-jdk-alpine
    container_name: api-processos
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
